[package]
name = "parmenides-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = { version = "0.19.0", default-features = false }
nutype = "0.5.0"
serde = { version = "1.0.215", features = ["derive"] }
thiserror = "2.0.3"
